# Supabase project config
# https://supabase.com/docs/guides/cli/config

project_id = "hmhhgmuuusknmucjlkth"

[api]
enabled = true

[db]
port = 54322
major_version = 15

[functions.haff-api]
verify_jwt = false
